### PR TITLE
add furrr variants

### PR DESCRIPTION
**Pull request by jeffzi**
Hi. 

First of all, thanks for this package. I started it to use it recently and it proved very useful. 

I created [furrr](https://github.com/DavisVaughan/furrr) variants of `_safely` and` _quietly` functions. They work via proxy `map, map2, pmap` functions that accept `.parallel` argument to dispatch to `purrr` or `furrr` implementations. The new variants are named `future_map_safely`, ... to follow furrr naming.

It solves #3 .

### CODE REVIEW

**Comment by jimjam-slam** [comment]
😮 Thanks so much! I'm planning to put a bunch of work into merging PRs next week over the holidays (still in the end-of-year work scramble at the moment), but I'm super here for this!

**Comment by jimjam-slam** [comment]
Okay, I've gotten there! I chose to merge this manually, as the other open PR reorganised things on the backend a little bit. It should be working on the [dev branch](https://github.com/rensa/collateral/tree/dev), although I'd love to throw some testing at these variants: they work with my very basic tests, but I haven't really put furrr through its paces much. I note that the `.progress` option doesn't seem to work, but I'm not sure if that's just because the examples I've tested are so basic.

Do you have an email address or URL, so that I can add you to the contributor list?

**Comment by jeffzi** [comment]
Nice, glad I could help.

Regarding the documentation, I think it would be good to add a note about `plan()`, similarly to what is done in the documentation of furrr. Maybe something along the lines:

> future variants rely on [furrr](https://github.com/DavisVaughan/furrr) and therefore [future](https://github.com/HenrikBengtsson/future) for parallelization. The default backend for `future` is a sequential one. This means that you still have to set an appropriate future strategy with `future::plan()`.

Regarding `.progress = TRUE`, I noticed that if processing is too fast furrr won't display the progress bar. This example works: 
``` r
library(collateral)
library(future)
plan(multiprocess)
future_map_safely(rep(2, 10), ~Sys.sleep(.x), .progress = TRUE)
#> 
 Progress:                                                          100%
 Progress: ──────────────────────                                   100%
 Progress: ──────────────────────                                   100%
 Progress: ────────────────────────────────────────────             100%
 Progress: ────────────────────────────────────────────             100%
 Progress: ────────────────────────────────────────────             100%
 Progress: ────────────────────────────────────────────             100%
 Progress: ────────────────────────────────────────────             100%
 Progress: ──────────────────────────────────────────────────────── 100%
 Progress: ──────────────────────────────────────────────────────── 100%
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
#> _ _
```
<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

> Do you have an email address or URL, so that I can add you to the contributor list?

Jean-Francois Zinque  - <jzinque@gmail.com>
Thanks !

**Comment by jimjam-slam** [comment]
Ah, awesome! I'll update the docs to suit (I might actually split the future variants into their own doc page to accommodate this) and add you to the contributors 🙂 Thanks so much, Jean-Francois!

**Pull request closed without merging**
