### PR TITLE
Map variants

### PR DESCRIPTION
**Pull request by romatik**
One commit to reduce duplication and make it easier to add new mappers https://github.com/rensa/collateral/commit/c5e3ccb0130c6d2c73cd0a0d92713ef60a196983
Second commit to show how documentation can be easier done with using markdown.

Feel free to merge either :)

### CODE REVIEW

**Comment by romatik** [comment]
There are no tests so not 100% certain it didn't change anything, but I ran example you provided and it worked exactly as before.

**Comment by jimjam-slam** [comment]
Thanks very much for the PR, Mikhail! I haven't had a chance to look at this this week (I'm in the middle of a house move 😒), but I'm hoping to this weekend. I submitted 0.4.2 to CRAN last weekend, but hopefully I can merge this in the next few days and it can make it into the next CRAN release (either in a couple months or, if this one gets knocked back, sooner) 🎉

**Comment by jimjam-slam** [comment]
(In the mean time, if you'd like to add yourself to the Description as a contributor, that is 💯 okay with me!)

**Comment by romatik** [comment]
Ok, I was thinking about it some more and I think your package can even be generalized some more and (potentially) merged in `purrr` itself. Basically, latest commit shows that there is no need for wrappers at all since what you are doing is not really modifying behavior of `map` and friends, but modifying output of a mapper. 

So by concentrating on that all you need to provide are two methods that are identical semantically to `purrr::safely` and `purrr::quietly`, but instead enhance their outputs (so they can be called `ensafely` and `enquietly` by analogy with `enquo` and stuff). This way you immediately get access to every single `map` variant without writing a single wrapper while retaining output that you want:
``` r
library(tidyverse)
library(collateral)

ex <- mtcars %>%
  rownames_to_column(var = "car") %>%
  as_data_frame() %>%
  select(car, cyl, disp, wt) %>%
  # spike some rows in cyl == 4 to make them fail
  mutate(wt = dplyr::case_when(
    wt < 2 ~ -wt,
    TRUE ~ wt)) %>%
  # nest and do some operations quietly()
  nest(-cyl) 


ex %>%
  mutate(qlog = map(data, quiet_mapper(~ log(.$wt))))
#> # A tibble: 3 x 3
#>     cyl data              qlog     
#>   <dbl> <list>            <list>   
#> 1     6 <tibble [7 × 3]>  <R O _ _>
#> 2     4 <tibble [11 × 3]> <R O _ W>
#> 3     8 <tibble [14 × 3]> <R O _ _>

ex %>%
  mutate(qlog = map(data, safe_mapper(~ stop("hallo"))))
#> # A tibble: 3 x 3
#>     cyl data              qlog  
#>   <dbl> <list>            <list>
#> 1     6 <tibble [7 × 3]>  <_ E> 
#> 2     4 <tibble [11 × 3]> <_ E> 
#> 3     8 <tibble [14 × 3]> <_ E>
```

<sup>Created on 2018-11-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romatik** [comment]
One more thing that I like a bit more with this approach that class of output in tibble stays the same (i.e., `list`, just like `data` is a `list` with special output for `tibble`), so, again, semantically nothing at all changes from the point of the view of the user, but you do get visual output of how your function behaved for different chunks.

**Comment by jimjam-slam** [comment]
So, the changes up to commit e290e34dea48d518957db2b6d73b2b9735270ed6 look like they don't change the API at all, and I like the reduction in duplication 😄 Also, using `type_sum()` to format the output instead of `pillar_shaft()` is really clever!

I like the idea of `ensafely()` and `enquietly()` a lot, although I think they'd be major version bumps. My main concern is that access to all the map variants might not necessarily be a good thing: for example, using them with `map_chr()` or `map_lgl()` wouldn't make a lot of sense. Although I'm not super fond of putting more map variants out, I think it makes sense because it sends a signal to the user about these functions' relationships to the other mappers. What do you think?

**Comment by romatik** [comment]
> for example, using them with map_chr() or map_lgl() wouldn't make a lot of sense.

`map_chr()` and `map_lgl()` don't make sense with `safely` and `quietly` either. 

What I'm trying to say is that your package can be a way for anyone familiar with `safely`/`quietly` to enhance their output without any change in semantics whatsoever. So, for example, if you want to use the function with `collaterall` it is as simple as replacing `purrr::safely` with `collateral::ensafely` anywhere. Changing `map` to `map_safely` is more work and overall sends a different message.

Moreover following scenario is possible in proposed approach:
```
safe_fn <- collateral::ensafely(unsafe_fn)
```
This function can be then passed around in a true functional programming style. Current API doesn't allow this flexibility, but it might be a tradeoff between usability and overall soundness of the concept. So it's your call :)

**Comment by jimjam-slam** [comment]
Okay, sorry for the looooong delay figuring this out. In the end I decided not to go with the wrapperless solution. I think the existing API using variant map functions makes the most sense, given the value of enhancing `safely()` and `quietly()` output is most important when you're iterating over many items.

But I did merge the rest of your commits—they're currently in the [dev branch](https://github.com/rensa/collateral/tree/dev). Thanks very much!

Do you have an email address or URL, so that I can add you to the contributor list?

**Pull request closed without merging**
